version: '3'
services:
  prestashop:
    container_name: some-presta
    image: my-presta:latest
    restart: always
    ports:
      - 8081:80
    environment:
      - DB_SERVER=some-mysql
      - DB_USER=root
      - DB_PASSWD=admin
    networks:
      - prestashop-net
    volumes:
      - app_data:/var/www/html
  db:
    container_name: some-my
    image: my-mysql:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - prestashop-net
    volumes:
      - mysql_data:/var/lib/mysql
networks:
  prestashop-net:
    driver: 'bridge'
volumes:
  app_data:
  mysql_data:
