version: '3'
services:
  prestashop:
    container_name: some-prestashop-ENVIR
    image: my-presta:latest
    restart: always
    ports:
      - 808ENVIR:80
    environment:
      - DB_SERVER=some-mysql
      - DB_USER=root
      - DB_PASSWD=admin
    networks:
      - prestashop-net-env-ENVIR
    volumes:
      - app_data_ENVIR:/var/www/html
  db:
    container_name: some-mysql-ENVIR
    image: my-mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - prestashop-net-env-ENVIR
    volumes:
      - mysql_data_ENVIR:/var/lib/mysql
networks:
  prestashop-net-env-ENVIR:
    driver: 'bridge'
volumes:
  app_data_ENVIR:
  mysql_data_ENVIR:
