version: '3'
services:
  prestashop:
    container_name: some-prestashop
    image: my-presta:latest
    restart: always
    ports:
      - 8082:80
    environment:
      - DB_SERVER=some-mysql
      - DB_USER=root
      - DB_PASSWD=admin
    networks:
      - prestashop-net-env-2
    volumes:
      - app_data_2:/var/www/html
  db:
    container_name: some-mysql
    image: my-mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    networks:
      - prestashop-net-env-$D_ENV
    volumes:
      - mysql_data_2:/var/lib/mysql
networks:
  prestashop-net-env-2:
    driver: 'bridge'
volumes:
  app_data_2:
  mysql_data_2:
